spring:
  application:
    name: smartlf
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss  # 全局统一的时间格式
    time-zone: GMT+8                  # 强制指定中国时区（极其重要，防止差 8 小时）
  ai:
    ollama:
      base-url: http://localhost:11434
      chat:
        model: qwen3.5:4b
  data:
    # redis配置
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      password: ${REDIS_PASSWORD}
      lettuce:
        pool:
          max-active: 10
          max-idle: 10
          min-idle: 1
          time-between-eviction-runs: 10s
  #数据库的连接信息
  datasource:
    #    url: jdbc:mysql://localhost:3306/dems
    url: jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
#Mybatis相关配置
mybatis-plus:
  map-underscore-to-camel-case: true
  global-config:
    db-config:
      id-type: auto # 全局设置主键生成策略为数据库自增
system:
  admin-secret-key: ${ADMIN_SECRET_KEY:QG-Studio-2026}
  file-prefix: ${SYSTEM.FILE-PREFIX:D:/upload/}
